basePath: /v1/tcpl
definitions:
  Calculation:
    properties:
      from:
        example: "2021-10-11T10:50:00+02:00"
        type: string
      machines:
        items:
          $ref: '#/definitions/Machine'
        type: array
      orders:
        items:
          $ref: '#/definitions/Order'
        type: array
      until:
        example: "2021-10-11T14:50:00+02:00"
        type: string
    type: object
  CreateOrder:
    properties:
      id:
        example: '#123AB'
        type: string
      machineId:
        example: BF007
        type: string
      plannedStart:
        example: "2021-10-11T10:00:00+02:00"
        type: string
    type: object
  Error:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: descriptive error message
        type: string
    type: object
  Machine:
    properties:
      id:
        example: BF007
        type: string
      totals:
        $ref: '#/definitions/Totals'
    type: object
  MachineIndex:
    properties:
      id:
        example: BF007
        type: string
    type: object
  Order:
    properties:
      id:
        example: '#123AB'
        type: string
      machineId:
        example: BF007
        type: string
      plannedStart:
        example: "2021-10-11T10:00:00+02:00"
        type: string
      startedAt:
        example: "2021-10-11T10:50:04+02:00"
        type: string
    type: object
  Totals:
    properties:
      energy:
        example: 115
        type: number
      energyUnit:
        example: kWh
        type: string
      length:
        example: 2124
        type: number
      lengthUnit:
        example: m
        type: string
      materialConsumption:
        example: 355
        type: number
      materialConsumptionExtruder1:
        example: 32.27
        type: number
      materialConsumptionExtruder1Component1:
        type: number
      materialConsumptionExtruder1Component2:
        type: number
      materialConsumptionExtruder1Component3:
        type: number
      materialConsumptionExtruder1Component4:
        type: number
      materialConsumptionExtruder1Component5:
        type: number
      materialConsumptionExtruder1Component6:
        type: number
      materialConsumptionExtruder2:
        example: 32.27
        type: number
      materialConsumptionExtruder2Component1:
        type: number
      materialConsumptionExtruder2Component2:
        type: number
      materialConsumptionExtruder2Component3:
        type: number
      materialConsumptionExtruder2Component4:
        type: number
      materialConsumptionExtruder2Component5:
        type: number
      materialConsumptionExtruder2Component6:
        type: number
      materialConsumptionExtruder3:
        example: 32.27
        type: number
      materialConsumptionExtruder3Component1:
        type: number
      materialConsumptionExtruder3Component2:
        type: number
      materialConsumptionExtruder3Component3:
        type: number
      materialConsumptionExtruder3Component4:
        type: number
      materialConsumptionExtruder3Component5:
        type: number
      materialConsumptionExtruder3Component6:
        type: number
      materialConsumptionExtruder4:
        example: 32.27
        type: number
      materialConsumptionExtruder4Component1:
        type: number
      materialConsumptionExtruder4Component2:
        type: number
      materialConsumptionExtruder4Component3:
        type: number
      materialConsumptionExtruder4Component4:
        type: number
      materialConsumptionExtruder4Component5:
        type: number
      materialConsumptionExtruder4Component6:
        type: number
      materialConsumptionExtruder5:
        example: 32.27
        type: number
      materialConsumptionExtruder5Component1:
        type: number
      materialConsumptionExtruder5Component2:
        type: number
      materialConsumptionExtruder5Component3:
        type: number
      materialConsumptionExtruder5Component4:
        type: number
      materialConsumptionExtruder5Component5:
        type: number
      materialConsumptionExtruder5Component6:
        type: number
      materialConsumptionExtruder6:
        example: 32.27
        type: number
      materialConsumptionExtruder6Component1:
        type: number
      materialConsumptionExtruder6Component2:
        type: number
      materialConsumptionExtruder6Component3:
        type: number
      materialConsumptionExtruder6Component4:
        type: number
      materialConsumptionExtruder6Component5:
        type: number
      materialConsumptionExtruder6Component6:
        type: number
      materialConsumptionExtruder7:
        example: 32.27
        type: number
      materialConsumptionExtruder7Component1:
        type: number
      materialConsumptionExtruder7Component2:
        type: number
      materialConsumptionExtruder7Component3:
        type: number
      materialConsumptionExtruder7Component4:
        type: number
      materialConsumptionExtruder7Component5:
        type: number
      materialConsumptionExtruder7Component6:
        type: number
      materialConsumptionExtruder8:
        example: 32.27
        type: number
      materialConsumptionExtruder8Component1:
        type: number
      materialConsumptionExtruder8Component2:
        type: number
      materialConsumptionExtruder8Component3:
        type: number
      materialConsumptionExtruder8Component4:
        type: number
      materialConsumptionExtruder8Component5:
        type: number
      materialConsumptionExtruder8Component6:
        type: number
      materialConsumptionExtruder9:
        example: 32.27
        type: number
      materialConsumptionExtruder9Component1:
        type: number
      materialConsumptionExtruder9Component2:
        type: number
      materialConsumptionExtruder9Component3:
        type: number
      materialConsumptionExtruder9Component4:
        type: number
      materialConsumptionExtruder9Component5:
        type: number
      materialConsumptionExtruder9Component6:
        type: number
      materialConsumptionExtruder10:
        example: 32.27
        type: number
      materialConsumptionExtruder10Component1:
        type: number
      materialConsumptionExtruder10Component2:
        type: number
      materialConsumptionExtruder10Component3:
        type: number
      materialConsumptionExtruder10Component4:
        type: number
      materialConsumptionExtruder10Component5:
        type: number
      materialConsumptionExtruder10Component6:
        type: number
      materialConsumptionExtruder11:
        example: 32.27
        type: number
      materialConsumptionExtruder11Component1:
        type: number
      materialConsumptionExtruder11Component2:
        type: number
      materialConsumptionExtruder11Component3:
        type: number
      materialConsumptionExtruder11Component4:
        type: number
      materialConsumptionExtruder11Component5:
        type: number
      materialConsumptionExtruder11Component6:
        type: number
      materialConsumptionUnit:
        example: kg
        type: string
      runTime:
        example: 4
        type: number
      runTimeUnit:
        example: h
        type: string
    type: object
host: localhost:1323
info:
  contact:
    email: robert.sliwinski@re-digital.io
    name: Robert Sliwinski
    url: http://r-ecosystem.de
  description: API for the ERP system to query the c.Hub for production parameters
    of each machine.
  termsOfService: http://r-ecosystem.de
  title: TCPL API
  version: "0.1"
paths:
  /calculations:
    get:
      consumes:
      - application/json
      description: Returns an object of calculations for a certain time period
      operationId: get-calculations
      parameters:
      - example: "2021-10-11T10:50:00+02:00"
        in: query
        name: from
        type: string
      - example: "2021-10-11T14:50:00+02:00"
        in: query
        name: until
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Calculation for a time period
          schema:
            $ref: '#/definitions/Calculation'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/Error'
      summary: Get calculations for a specific time period
      tags:
      - Calculations
  /machines:
    get:
      consumes:
      - application/json
      description: Returns an array of all known machines from the time-series database
      operationId: get-machines
      produces:
      - application/json
      responses:
        "200":
          description: An collection of machines
          schema:
            items:
              $ref: '#/definitions/MachineIndex'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/Error'
      summary: Get all machines
      tags:
      - Machines
  /order:
    post:
      consumes:
      - application/json
      description: Create an order inside the machines HMI
      operationId: post-order
      parameters:
      - description: Create an Order Object
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/CreateOrder'
      produces:
      - application/json
      responses:
        "201":
          description: Inserted Order
          schema:
            $ref: '#/definitions/CreateOrder'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/Error'
      summary: Create order in machines HMI
      tags:
      - Order
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
